---
name: Commit
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: extenda/actions/gcp-secret-manager@v0
        with:
          service-account-key: ${{ secrets.SECRET_AUTH }}
          secrets: |
            NEXUS_PASSWORD: nexus-password
            NEXUS_USERNAME: nexus-username

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Determine version
        uses: extenda/actions/conventional-version@v0
        id: semver
        with:
          version-suffix: -SNAPSHOT

      - name: Run tests
        uses: extenda/actions/maven@v0
        with:
          args: verify -fae
          version: ${{ steps.semver.outputs.version }}

      - name: Analyze with SonarCloud
        uses: extenda/actions/sonar-scanner@v0
        with:
          sonar-host: https://sonarcloud.io
          main-branch: ${{ steps.semver.outputs.branch-name-short }}
          maven-args: --file pom.xml sonar:sonar
          service-account-key: ${{ secrets.SECRET_AUTH }}

  staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      #     - uses: extenda/actions/gcp-secret-manager@v0
      #       with:
      #         service-account-key: ${{ secrets.SECRET_AUTH }}
      #         secrets: |
      #           NEXUS_PASSWORD: nexus-password
      #           NEXUS_USERNAME: nexus-username

      #     - name: Set up JDK 11
      #       uses: actions/setup-java@v1
      #       with:
      #         java-version: 11

      #     - uses: actions/cache@v1
      #       with:
      #         path: ~/.m2/repository
      #         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      #         restore-keys: |
      #           ${{ runner.os }}-maven-

      #     - name: Create release
      #       uses: extenda/actions/conventional-release@v0
      #       id: release
      #       env:
      #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #     - name: Delpoy to Nexus release
      #       uses: extenda/actions/maven@v0
      #       with:
      #         args: deploy -DskipTests
      #         version: ${{ steps.release.outputs.version }}

      - name: Setup gcloud
        uses: extenda/actions/setup-gcloud@v0
        with:
          service-account-key: ${{ secrets.GCLOUD_AUTH_STAGING }}

          - name: Auth Docker for GCP
            run: gcloud --quiet auth configure-docker

          - name: Build Docker image with Quarkus and push
            uses: extenda/actions/maven@v0
            with:
              args: >
                clean package -DskipTests
                -Dquarkus.container-image.build=true
                -Dquarkus.container-image.push=true
                -Dquarkus.container-image.registry=eu.gcr.io
                -Dquarkus.container-image.group=extenda
                -Dquarkus.container-image.name=hiiretail-rra-extractor
                -Dquarkus.container-image.tag=${{ steps.release.outputs.release-tag }}

          - name: Deploy to staging
            uses: extenda/actions/cloud-run@v0
            with:
              service-account-key: ${{ secrets.GCLOUD_AUTH_STAGING }}
              image: eu.gcr.io/extenda/hiiretail-rra-extractor:${{ steps.release.outputs.release-tag }}

  production:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2

      - uses: extenda/actions/gcp-secret-manager@v0
        with:
          service-account-key: ${{ secrets.SECRET_AUTH }}
          secrets: |
            STYRA_TOKEN: styra-das-token

      - uses: extenda/actions/setup-gcloud@v0
        id: gcloud
        with:
          service-account-key: ${{ secrets.GCLOUD_AUTH_PROD }}

      - name: Deploy to Production
        uses: extenda/actions/cloud-run@v0
        with:
          service-account-key: ${{ secrets.GCLOUD_AUTH_PROD }}
          image: ${{ needs.release.outputs.release-image }}
