# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [feat/* ]
  pull_request:
    branches: [ master ]
    #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '*/15 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Parameters matrix
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        jdk: [8, 11, 14]

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
